---
title: "data_tidying"
author: "Hannah Garcia"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(dplyr)
```


```{r}
# read in sheet and clean names
oak_collapse_sheet <- read.csv(here("intensified_2021_data", "final_txpt_20210915.csv")) %>% 
  clean_names()

# cleaned up sheets for google sheet oak collapse
intensified_oak_sheet <- oak_collapse_sheet %>% 
  select(plot, poin, tree, azimuth, dist, dbhi, spec, lvdd) %>% 
  rename(subplot = poin) %>% 
  filter(spec %in% c("QUCH2", "QUKE")) %>% 
  mutate(spec = case_when(
    spec == "QUCH2" ~ "QUCH",
    spec == "QUKE" ~ "QUKE")) %>% 
  rename(species = spec) %>% 
  filter(lvdd == "L")

# get rid of duplicate observations
intensified_oak_sheet_final <- intensified_oak_sheet %>% 
  dplyr::distinct(plot, subplot, tree, .keep_all = TRUE) %>% 
  filter(dbhi >= 4)

# save as file to export to google sheets
# write.csv(intensified_oak_sheet_final, here("intensified_data_2021/intensified_oaks.csv"), row.names = FALSE)

```

# Combine collapsed data back into original datasheet
```{r}
# Read in csv

oak_collapse_final <- read.csv(here("intensified_data_2021", "intensified_oak_collapse_final.csv")) 

raw_data <- read.csv(here("intensified_data_2021", "final_txpt_20210915.csv")) %>% 
  clean_names() %>% 
  rename(subplot = poin) %>% 
  filter(lvdd == "L") %>% 
  rename(species = spec)
  
oaks_raw <- raw_data %>% 
  filter(species %in% c("QUCH2", "QUKE")) %>% 
  mutate(species = case_when(
    species == "QUCH2" ~ "QUCH",
    species == "QUKE" ~ "QUKE")) 

# merge the raw oaks with the collapsed oaks
oaks_join <- merge(oaks_raw, oak_collapse_final, 
                          by = c("plot", "subplot")) %>% 
  dplyr::distinct(plot, subplot, tree, .keep_all = TRUE)
  
```









